// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @title MockGroth16Verifier
/// @notice Mock Groth16 verifier for testing and development
/// @dev In production, replace this with the actual Groth16Verifier generated by snarkjs
contract MockGroth16Verifier {
    /// @notice Verify a Groth16 proof
    /// @param proof The proof to verify (simplified format)
    /// @param publicSignals Public signals from the proof
    /// @return isValid True if proof is valid
    /// @dev This is a mock implementation - in production, use actual Groth16 verification
    function verify(
        uint256[8] memory proof,
        uint256[] memory publicSignals
    ) public pure returns (bool isValid) {
        // Mock verification - always returns true for testing
        // In production, this would perform actual Groth16 verification
        // using pairing checks on bn128 curve
        
        // Basic validation: check that inputs are non-zero
        if (publicSignals.length == 0) {
            return false;
        }
        
        // For testing, accept any non-zero proof
        // In production, replace with actual Groth16 verification logic
        return true;
    }

    /// @notice Verify proof with custom format (for compatibility)
    function verifyProof(
        uint256[2] memory a,
        uint256[2][2] memory b,
        uint256[2] memory c,
        uint256[] memory publicSignals
    ) public pure returns (bool) {
        // Convert to standard format and verify
        uint256[8] memory proof;
        proof[0] = a[0];
        proof[1] = a[1];
        proof[2] = b[0][0];
        proof[3] = b[0][1];
        proof[4] = b[1][0];
        proof[5] = b[1][1];
        proof[6] = c[0];
        proof[7] = c[1];
        return verify(proof, publicSignals);
    }
}

