// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Script, console} from "forge-std/Script.sol";

/// @title DeployGroth16Verifier
/// @notice Deployment script for the generated Groth16Verifier contract
/// @dev This script deploys the verifier generated by snarkjs
contract DeployGroth16Verifier is Script {
    function run() external {
        uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");
        vm.startBroadcast(deployerPrivateKey);

        address deployer = vm.addr(deployerPrivateKey);
        console.log("Deployer address:", deployer);
        console.log("");

        // Read the generated verifier contract
        // Note: In production, you would import the actual Groth16Verifier contract
        // For now, we'll check if it exists and provide instructions
        
        string memory verifierPath = "contracts/generated/Groth16Verifier.sol";
        
        try vm.readFile(verifierPath) returns (string memory) {
            console.log("Found generated Groth16Verifier.sol");
            console.log("");
            console.log("To deploy:");
            console.log("  1. Copy contracts/generated/Groth16Verifier.sol to src/verifiers/");
            console.log("  2. Import it in your deployment script");
            console.log("  3. Deploy: new Groth16Verifier()");
            console.log("");
            console.log("Or use Remix/Hardhat to deploy the contract directly.");
        } catch {
            console.log("ERROR: Groth16Verifier.sol not found!");
            console.log("");
            console.log("Please run the generation script first:");
            console.log("  powershell -ExecutionPolicy Bypass -File scripts\\generate-groth16-verifier-auto.ps1");
            console.log("");
        }

        vm.stopBroadcast();
    }
}

